source_file_path:
- main.hip
target_kernel_functions:
- callback
compile_command:
- make
correctness_command:
- ./rocfft_callback
performance_command:
- ./rocfft_callback
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
