source_file_path:
- main.hip
target_kernel_functions:
- prefix_sum
compile_command:
- make
correctness_command:
- ./applications_prefix_sum
performance_command:
- ./applications_prefix_sum
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
