source_file_path:
- main.hip
target_kernel_functions:
- device_ptr
compile_command:
- make
correctness_command:
- ./rocthrust_device_ptr
performance_command:
- ./rocthrust_device_ptr
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
