source_file_path:
- main.hip
target_kernel_functions:
- dynamic_shared
compile_command:
- make
correctness_command:
- ./hip_dynamic_shared
performance_command:
- ./hip_dynamic_shared
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
