source_file_path:
- main.hip
target_kernel_functions:
- reduce_sum
compile_command:
- make
correctness_command:
- ./rocthrust_reduce_sum
performance_command:
- ./rocthrust_reduce_sum
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
