source_file_path:
- main.hip
target_kernel_functions:
- saxpy
compile_command:
- make
correctness_command:
- ./rocthrust_saxpy
performance_command:
- ./rocthrust_saxpy
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
