source_file_path:
- main.hip
target_kernel_functions:
- module_api
compile_command:
- make
correctness_command:
- ./hip_module_api
performance_command:
- ./hip_module_api
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
