source_file_path:
- src/ball_query_cuda.hip
target_kernel_functions:
- ball_query
compile_command:
- python3 test_ball_query.py
correctness_command:
- python3 test_ball_query.py
performance_command:
- python3 test_ball_query.py
task_type: hip2hip
task_result_template: task_result_template_double_output_perf.yaml
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
