source_file_path:
- main.hip
target_kernel_functions:
- device_sum
compile_command:
- make
correctness_command:
- ./hipcub_device_sum
performance_command:
- ./hipcub_device_sum
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
