source_file_path:
- main.hip
target_kernel_functions:
- gpu_arch
compile_command:
- make
correctness_command:
- ./hip_gpu_arch
performance_command:
- ./hip_gpu_arch
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
