source_file_path:
- main.hip
target_kernel_functions:
- runtime_compilation
compile_command:
- make
correctness_command:
- ./hip_runtime_compilation
performance_command:
- ./hip_runtime_compilation
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
