source_file_path:
- src/gather_points_cuda.hip
target_kernel_functions:
- gather_points_kernel
- gather_points_grad_kernel
compile_command:
- python3 scripts/task_runner.py compile
correctness_command:
- python3 scripts/task_runner.py correctness
performance_command:
- python3 scripts/task_runner.py performance
task_type: hip2hip
task_result_template: task_result_template_double_output_perf.yaml
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
