source_file_path:
- src/roiaware_pool3d_kernel.hip
target_kernel_functions:
- roiaware_pool3d
compile_command:
- python3 test_roiaware_pool3d.py
correctness_command:
- python3 test_roiaware_pool3d.py
performance_command:
- python3 test_roiaware_pool3d.py
task_type: hip2hip
task_result_template: task_result_template_double_output_perf.yaml
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
