source_file_path:
- src/furthest_point_sample_cuda.hip
target_kernel_functions:
- furthest_point_sample
compile_command:
- python3 test_furthest_point_sample.py
correctness_command:
- python3 test_furthest_point_sample.py
performance_command:
- python3 test_furthest_point_sample.py
task_type: hip2hip
task_result_template: task_result_template_double_output_perf.yaml
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
