source_file_path:
- main.hip
target_kernel_functions:
- histogram
compile_command:
- make
correctness_command:
- ./applications_histogram
performance_command:
- ./applications_histogram
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
