source_file_path:
- main.hip
target_kernel_functions:
- bit_extract
compile_command:
- make
correctness_command:
- ./hip_bit_extract
performance_command:
- ./hip_bit_extract
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
