source_file_path:
- main.hip
target_kernel_functions:
- gemm_strided_batched
compile_command:
- make
correctness_command:
- ./hipblas_gemm_strided_batched
performance_command:
- ./hipblas_gemm_strided_batched
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
