source_file_path:
- main.hip
target_kernel_functions:
- bandwidth
compile_command:
- make
correctness_command:
- ./hip_bandwidth
performance_command:
- ./hip_bandwidth
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
