source_file_path:
- main.hip
target_kernel_functions:
- norm
compile_command:
- make
correctness_command:
- ./rocthrust_norm
performance_command:
- ./rocthrust_norm
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
