source_file_path:
- main.hip
target_kernel_functions:
- her
compile_command:
- make
correctness_command:
- ./hipblas_her
performance_command:
- ./hipblas_her
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
