source_file_path:
- main.hip
target_kernel_functions:
- texture_management
compile_command:
- make
correctness_command:
- ./hip_texture_management
performance_command:
- ./hip_texture_management
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
