source_file_path:
- main.hip
target_kernel_functions:
- remove_points
compile_command:
- make
correctness_command:
- ./rocthrust_remove_points
performance_command:
- ./rocthrust_remove_points
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
