source_file_path:
- main.hip
target_kernel_functions:
- occupancy
compile_command:
- make
correctness_command:
- ./hip_occupancy
performance_command:
- ./hip_occupancy
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
