source_file_path:
- main.hip
target_kernel_functions:
- static_device_library
compile_command:
- make
correctness_command:
- ./hip_static_device_library
performance_command:
- ./hip_static_device_library
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
