source_file_path:
- main.hip
target_kernel_functions:
- floyd_warshall
compile_command:
- make
correctness_command:
- ./applications_floyd_warshall
performance_command:
- ./applications_floyd_warshall
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
