source_file_path:
- main.hip
target_kernel_functions:
- moving_average
compile_command:
- make
correctness_command:
- ./hip_moving_average
performance_command:
- ./hip_moving_average
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
