source_file_path:
- main.hip
target_kernel_functions:
- monte_carlo_pi
compile_command:
- make
correctness_command:
- ./applications_monte_carlo_pi
performance_command:
- ./applications_monte_carlo_pi
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
