source_file_path:
- main.hip
target_kernel_functions:
- point_to_voxelidx
compile_command:
- make
correctness_command:
- ./applications_point_to_voxelidx
performance_command:
- ./applications_point_to_voxelidx
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null