source_file_path:
- main.hip
target_kernel_functions:
- cooperative_groups
compile_command:
- make
correctness_command:
- ./hip_cooperative_groups
performance_command:
- ./hip_cooperative_groups
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
