source_file_path:
- main.hip
target_kernel_functions:
- warp_shuffle
compile_command:
- make
correctness_command:
- ./hip_warp_shuffle
performance_command:
- ./hip_warp_shuffle
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
