source_file_path:
- main.hip
target_kernel_functions:
- assembly_to_executable
compile_command:
- make
correctness_command:
- ./hip_assembly_to_executable
performance_command:
- ./hip_assembly_to_executable
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
