source_file_path:
- main.hip
target_kernel_functions:
- bitonic_sort
compile_command:
- make
correctness_command:
- ./applications_bitonic_sort
performance_command:
- ./applications_bitonic_sort
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
